### ISSUE TITLE
'characters' is deprecated: Please use String or Substring directly

### ISSUE THREAD

**Issue by rapholivera** [Edudjr/TLCustomMask#5]
![screen shot 2018-02-16 at 14 34 25](https://user-images.githubusercontent.com/19297611/36318289-8ae05f12-1326-11e8-8db0-b51a4fa106ef.png)
![screen shot 2018-02-16 at 14 34 36](https://user-images.githubusercontent.com/19297611/36318294-90b2577e-1326-11e8-9f9a-e39b6ff218f8.png)

**Comment by Edudjr** [comment]
Issue resolved by #6
